import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./burger.css"; // هنعمل الملف ده دلوقتي
import { Analytics } from "@vercel/analytics/react";
import Navbar from "./_components/navbar";
import Footer from "./_components/footer";

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata = {
   title: "Hamdi Emad's Portfolio",
   description: "Generated by create next app",
   icons: {
      icon: "/favicon.ico", // لو اسم الصورة favicon.ico بدلها هنا
   },
};

export default function RootLayout({ children }) {
   return (
      <html lang="en" className="scroll-smooth">
         <head>
            <link
               rel="stylesheet"
               href="https://unpkg.com/aos@next/dist/aos.css"
            />
         </head>
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#141819] page-holder `}
         >
            <Navbar />
            {children}
            <Footer />
            <Analytics />
         </body>
      </html>
   );
}
